'use strict';
const $=s=>document.querySelector(s);
const KEY='strength-week-v1';
let stored={};
try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{}
const state={mode:stored.mode==='full'?'full':'reduced',day:DAYS[stored.day]?stored.day:'a',choices:stored.choices||{},optional:stored.optional||{},logs:stored.logs||{},weights:stored.weights||{}};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let date=today();
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>$('#toast').style.display='none',3500);}
let saveFailed=false;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{if(!saveFailed){toast('Browser storage is unavailable. This session will not persist.');saveFailed=true;}}}
function selected(s){const choice=s.options.includes(state.choices[s.id])?state.choices[s.id]:s.options[0];return state.mode==='reduced'&&EXERCISES[choice].upper?(s.options.find(id=>!EXERCISES[id].upper)||choice):choice;}
function slotsForDay(){const day=DAYS[state.day];return day.slots.filter(s=>state.mode==='full'||day.reduced.includes(s.id)).filter(s=>state.mode==='full'||!EXERCISES[selected(s)].upper).sort((a,b)=>{if(state.day!=='c')return 0;const rank=s=>s.id==='c-leg1'?0:selected(s)==='rdl'?1:s.id==='c-row'?2:s.id==='c-press'?3:4;return rank(a)-rank(b);});}
function numberOfSets(s){return selected(s)==='walk'?1:s.coreSlot?s.sets:state.mode==='reduced'||EXERCISES[selected(s)].later?2:s.sets;}
function logKey(s){return [date,state.mode,state.day,s.id,selected(s)].join('|');}
function log(s){const k=logKey(s);return state.logs[k]||(state.logs[k]={done:[],reps:[]});}
function isOptional(s){return s.optional||(state.mode==='reduced'&&EXERCISES[selected(s)].group==='Core');}
function isActive(s){return !isOptional(s)||(state.optional[s.id]??!!s.defaultActive);}
function renderTabs(){const root=$('.day-tabs');root.innerHTML=Object.entries(DAYS).map(([key,d])=>`<button class="day-tab" id="tab-${key}" role="tab" aria-selected="${state.day===key}" aria-controls="workout" tabindex="${state.day===key?0:-1}" data-day="${key}"><span class="letter">${key.toUpperCase()}</span><span><strong>${d.label}</strong><span class="day-name">${d.day}</span></span></button>`).join('');}
function updateProgress(){const slots=slotsForDay().filter(isActive);let count=0,total=0;for(const s of slots){const n=numberOfSets(s);total+=n;count+=log(s).done.slice(0,n).filter(Boolean).length;}$('#progress-text').textContent=`${count} of ${total} sets / activity blocks complete`;$('#set-total').textContent=state.mode==='full'?'Future target · build gradually':'Reduced starting volume';$('#progress-bar').style.width=total?`${count/total*100}%`:'0%';}
function inlineVisual(id){
 const e=EXERCISES[id];
 if(e.gif){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;return `<figure class="exercise-visual"><div class="inline-stage" data-visual="${id}">${reduced?'<p>Animation paused for your motion preference.</p>':`<img src="${esc(e.gif)}" loading="lazy" width="600" height="600" referrerpolicy="no-referrer" alt="${esc(e.name)} movement demonstration" data-inline-image="${id}">`}</div><figcaption><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">StrengthLog · form guide ↗</a><button class="text-btn" data-toggle-animation="${id}" aria-pressed="${!reduced}">${reduced?'Play':'Pause'}</button></figcaption></figure>`;}
 if(e.video)return `<figure class="exercise-visual"><div class="inline-stage video-preview"><button data-inline-video="${id}" aria-label="Play ${esc(e.name)} demonstration"><img src="https://i.ytimg.com/vi/${e.video}/hqdefault.jpg" loading="lazy" width="480" height="360" referrerpolicy="no-referrer" alt="${esc(e.name)} video preview"><span class="play-label">▶ Watch technique</span></button></div><figcaption><a href="${esc(e.videoUrl)}" target="_blank" rel="noopener noreferrer">${esc(e.videoSource)} · video ↗</a></figcaption></figure>`;
 return `<figure class="exercise-visual"><div class="inline-stage"><img src="assets/walk.svg" width="600" height="600" alt="Walking posture illustration: relaxed arms, upright trunk and comfortable stride"></div><figcaption>Easy pace · conversation should feel comfortable</figcaption></figure>`;
}
function loadGuidance(id){const e=EXERCISES[id];if(id==='walk')return '20–30 minutes at an easy conversational pace. Shorten if needed.';if(e.bodyweight||['bridge','deadbug','stepup'].includes(id))return 'Start with bodyweight (0 kg added). Improve control before adding resistance.';if(id==='pushup')return 'Bodyweight. Raise your hands on a stable surface to reduce difficulty; no added weight.';return `Use a load for ${e.reps} controlled reps with 2–3 more clean reps possible. Start with a light practice set; lower the weight if form changes or symptoms increase.`;}
function renderWorkout(){
 const day=DAYS[state.day];$('#mode').value=state.mode;renderTabs();$('#day-title').textContent=`${state.day.toUpperCase()} / ${day.label}`;$('#day-description').textContent=day.desc;
 $('#mode-note').innerHTML=state.mode==='reduced'?'<strong>Reduced view · keep it comfortable.</strong>Start with two sets of the lower-body movements shown. Upper-body work is held while shoulder symptoms are assessed. No exercise is automatically suitable; omit anything that provokes symptoms. A short session is fine.':'<strong>Future full routine · after assessment and exercise selection.</strong>These are targets to build toward, not a prescription to start all at once. Choose only individually tolerated movements. Stop for increasing pain, compensating technique or next-morning worsening. Switching this view does not establish medical clearance.';
 const slots=slotsForDay();
 $('#workout').setAttribute('role','tabpanel');$('#workout').setAttribute('aria-labelledby',`tab-${state.day}`);
 $('#workout').innerHTML=slots.map((s,i)=>{
 const id=selected(s),e=EXERCISES[id],n=numberOfSets(s),l=log(s),active=isActive(s);
 const optional=isOptional(s)?`<label class="optional-control"><input type="checkbox" data-optional="${s.id}" ${active?'checked':''}>${s.coreSlot?(s.defaultActive?'Include core':'Include optional core'):'Include optional'} ${e.name.toLowerCase()} (${n} ${id==='walk'?'block':'sets'})</label>`:'';
 if(!active)return `${optional}<div class="optional-disabled">Optional work is off. Add it only if recovered and time permits.</div>`;
 return `${optional}<article class="exercise-row ${l.done.slice(0,n).filter(Boolean).length===n?'completed':''}" data-slot="${s.id}"><div class="row-top"><span class="exercise-number">${i+1}</span><div class="exercise-title"><span class="exercise-group">${esc(e.group)}</span><h4>${esc(e.name)}</h4><span class="equipment">${esc(e.equipment)}</span></div><span class="dose">${id==='walk'?'20–30 min':`${n} × ${e.reps}`}</span></div><div class="exercise-body">${inlineVisual(id)}<div class="exercise-instructions"><h5>How to do it</h5><p class="cue">${esc(e.cue)}</p><ol class="inline-tips">${e.tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>${e.upper?`<p class="hold-note">${e.later?'Later option. Start with two light sets. ':'After shoulder assessment. '}Use only if individually tolerated; stop if pain increases or symptoms are worse the next morning.</p>`:''}<div class="recommended-load"><h5>Recommended load</h5><p>${esc(loadGuidance(id))}</p><p class="load-specific">${esc(e.load)}</p></div></div></div><div class="exercise-log"><div class="weight-fields"><label>${id==='walk'?'Duration · minutes':'Working weight · kg'}<input type="number" min="0" max="2000" step="0.1" data-weight="${id}" value="${esc(state.weights[id]??'')}" placeholder="${(e.bodyweight||['bridge','deadbug','stepup','pushup'].includes(id))?'0 added':'Enter load'}" aria-label="${esc(e.name)} ${id==='walk'?'minutes':'weight in kilograms'}"></label><label>Reps per set<input type="text" maxlength="35" data-reps="${s.id}" value="${esc(l.actual||'')}" placeholder="12, 11, 10" aria-label="${esc(e.name)} actual repetitions"></label></div><p class="small">${e.equipment.includes('Dumbbell')||e.equipment.includes('dumbbell')?'Dumbbell weight is per hand. ':''}Saved load is your record, not an automatic recommendation to repeat or increase it.</p><div class="row-controls"><div><span class="set-label">Tap each completed ${id==='walk'?'block':'set'}</span><div class="set-checks">${Array.from({length:n},(_,j)=>`<button class="set-check" data-set="${j}" data-slot="${s.id}" aria-label="${esc(e.name)} ${id==='walk'?'activity':'set'} ${j+1} complete" aria-pressed="${!!l.done[j]}">${l.done[j]?'✓':j+1}</button>`).join('')}</div></div><div class="row-actions"><button class="demo-btn" data-rest="${['Back','Chest','Legs'].includes(e.group)?120:90}">Rest · ${['Back','Chest','Legs'].includes(e.group)?'2 min':'90 sec'}</button><button class="text-btn" data-detail="${id}">More detail ↗</button></div></div></div><details class="row-more"><summary>Change exercise</summary><div class="row-settings"><label>Replace this exercise<select data-swap="${s.id}" aria-label="Choose exercise for ${s.id}">${s.options.filter(k=>state.mode==='full'||!EXERCISES[k].upper).map(k=>`<option value="${k}" ${k===id?'selected':''}>${esc(EXERCISES[k].name)}</option>`).join('')}</select></label></div><p class="small">The new exercise replaces this slot and updates the demonstration. It does not add sets.</p></details></article>`;
 }).join('');
 $('#workout-tail').innerHTML=`<div class="core-note"><strong>Core goes last · one exercise first, a second if recovered.</strong> A, B and C each start with one 2-set core movement (6 weekly sets). The second movement is optional and adds only 1 set. Build toward 6–9 weekly sets gradually; this is a starting range, not a target to force. D has two optional 1-set choices: use them as easy practice or to replace missed core, and skip them after hard core work the previous day. <a href="#core-plan">Order & core plan ↗</a></div><p class="small">Allow roughly 5–10 minutes for core. If 50–60 minutes runs out, omit the second core exercise or one arm-isolation slot rather than rushing the main lifts or cutting their rest.</p>`;
 updateProgress();
}
function renderLibrary(){const query=$('#search').value.trim().toLowerCase(),group=$('#group-filter').value;const list=Object.entries(EXERCISES).filter(([,e])=>(group==='all'||group===e.group)&&`${e.name} ${e.group} ${e.equipment} ${e.why}`.toLowerCase().includes(query));$('#exercise-library').innerHTML=list.length?list.map(([id,e])=>`<article class="library-card"><span class="tag ${e.upper?'conditional':''}">${e.group.toUpperCase()}${e.upper?' · AFTER ASSESSMENT':''}</span><h3>${esc(e.name)}</h3><span class="equipment">${esc(e.equipment)}</span><p>${esc(e.why)}</p><button class="demo-btn" data-detail="${id}">Technique & demonstration ↗</button></article>`).join(''):'<p class="empty">No exercises match. Try another name or muscle group.</p>';}
function renderGallery(){$('#card-gallery').innerHTML=Object.entries(DAYS).map(([key,d])=>`<figure><a href="assets/day-${key}.png" target="_blank" rel="noopener" aria-label="Open ${d.label} infographic"><img src="assets/day-${key}.png" loading="lazy" width="941" height="1672" alt="${d.day}: ${d.label} illustrated baseline workout. Future full plan except optional day D."></a><figcaption>${key.toUpperCase()} / ${d.label}</figcaption><a href="assets/day-${key}.png" download="strength-week-${key}.png">Save card ↓</a></figure>`).join('');}
function openDetail(id){const e=EXERCISES[id];if(!e)return;const hasMedia=e.gif||e.video;$('#dialog-content').innerHTML=`<span class="tag ${e.upper?'conditional':''}">${e.group}${e.upper?' · After assessment':''}</span><h2 style="margin-top:16px">${esc(e.name)}</h2><p class="dialog-cue">${esc(e.cue)}</p>${e.upper?'<div class="hold-note">This movement loads the shoulder. Use only after assessment and when individually tolerated; popularity is not proof of suitability.</div>':''}<div class="media-stage" id="media-stage">${hasMedia?`<button class="primary" data-load-media="${id}">▶ Load ${e.gif?'animation':'video'}</button><p>Loads from ${e.gif?'StrengthLog / WordPress image hosting':esc(e.videoSource||'YouTube')}. The full video loads on play. Inline workout animations may already be visible.</p>`:`<p>Use the original provider's demonstration for this movement.</p><a class="primary" href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Open demonstration guide ↗</a>`}</div><p class="dialog-provider">${e.gif?'Animation: StrengthLog. ':e.video?'Video: '+esc(e.videoSource)+'. ':''}<a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Original instructions & demonstration ↗</a></p><ol class="dialog-tips">${e.tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p class="load-note"><strong>Choosing the load</strong><br>${esc(e.load)}</p>${e.alternatives.length?`<p class="small">Alternatives replace this exercise; they are not extra mandatory work.</p><div class="row-actions">${e.alternatives.map(k=>`<button class="text-btn" data-detail="${k}">${esc(EXERCISES[k].name)} ↗</button>`).join('')}</div>`:''}`;if(!$('#exercise-dialog').open)$('#exercise-dialog').showModal();}
function loadMedia(id){const e=EXERCISES[id],stage=$('#media-stage');stage.replaceChildren();if(e.gif){const img=document.createElement('img');img.alt=`${e.name} movement demonstration by StrengthLog`;img.referrerPolicy='no-referrer';img.src=e.gif;img.addEventListener('error',()=>{stage.innerHTML='<p>The animation could not load. Use the original demonstration link below.</p>';});stage.append(img);const stop=document.createElement('button');stop.textContent='Stop animation';stop.className='outline';stop.onclick=()=>openDetail(id);stage.append(stop);}else{const iframe=document.createElement('iframe');iframe.title=`${e.name} demonstration`;iframe.src=`https://www.youtube-nocookie.com/embed/${e.video}`;iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allow='accelerometer; encrypted-media; gyroscope; picture-in-picture';iframe.allowFullscreen=true;stage.append(iframe);const a=document.createElement('a');a.href=e.videoUrl;a.textContent='If unavailable, watch on YouTube ↗';a.target='_blank';a.rel='noopener noreferrer';stage.append(a);}}
let remaining=120,deadline=null,timerInterval=null;
function paintTimer(){$('#timer-display').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('#timer-start').textContent=deadline?'Pause':remaining===0?'Restart':'Start';}
function tick(){if(!deadline)return;remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(remaining===0){deadline=null;clearInterval(timerInterval);$('#timer-announcement').textContent='Rest finished.';toast('Rest finished. Continue when ready.');}paintTimer();}
function startTimer(seconds){clearInterval(timerInterval);remaining=seconds;deadline=Date.now()+remaining*1000;$('#timer-duration').value=String(seconds);timerInterval=setInterval(tick,250);paintTimer();}
document.addEventListener('click',event=>{
 const target=event.target.closest('button');if(!target)return;
 if(target.dataset.day){state.day=target.dataset.day;save();renderWorkout();$(`#tab-${state.day}`).focus({preventScroll:true});$('#day-title').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 if(target.dataset.toggleAnimation){const id=target.dataset.toggleAnimation,stage=target.closest('figure').querySelector('.inline-stage'),playing=target.getAttribute('aria-pressed')==='true';stage.innerHTML=playing?'<p>Animation paused. Use the form cues beside this card.</p>':`<img src="${esc(EXERCISES[id].gif)}" width="600" height="600" referrerpolicy="no-referrer" alt="${esc(EXERCISES[id].name)} movement demonstration" data-inline-image="${id}">`;target.setAttribute('aria-pressed',String(!playing));target.textContent=playing?'Play':'Pause';}
 if(target.dataset.inlineVideo){const e=EXERCISES[target.dataset.inlineVideo];target.closest('.inline-stage').innerHTML=`<iframe title="${esc(e.name)} demonstration" src="https://www.youtube-nocookie.com/embed/${e.video}?autoplay=1" allow="autoplay; encrypted-media; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`;}
 if(target.dataset.detail)openDetail(target.dataset.detail);
 if(target.dataset.loadMedia)loadMedia(target.dataset.loadMedia);
 if(target.dataset.set!==undefined){const s=DAYS[state.day].slots.find(s=>s.id===target.dataset.slot);const index=Number(target.dataset.set);log(s).done[index]=!log(s).done[index];save();target.setAttribute('aria-pressed',String(!!log(s).done[index]));target.textContent=log(s).done[index]?'✓':index+1;target.closest('.exercise-row').classList.toggle('completed',log(s).done.slice(0,numberOfSets(s)).filter(Boolean).length===numberOfSets(s));updateProgress();}
 if(target.dataset.rest)startTimer(Number(target.dataset.rest));
});
document.addEventListener('change',event=>{const t=event.target;if(t.dataset.swap){const s=DAYS[state.day].slots.find(s=>s.id===t.dataset.swap);if(s.options.includes(t.value)){state.choices[s.id]=t.value;save();renderWorkout();toast('Exercise swapped. Set allowance stays the same.');}}if(t.dataset.optional){state.optional[t.dataset.optional]=t.checked;save();renderWorkout();}});
document.addEventListener('input',event=>{const t=event.target;if(t.dataset.weight){const val=Number(t.value);if(t.value===''||(Number.isFinite(val)&&val>=0&&val<=2000)){state.weights[t.dataset.weight]=t.value;save();}}if(t.dataset.reps){const s=DAYS[state.day].slots.find(s=>s.id===t.dataset.reps);log(s).actual=t.value.slice(0,35);save();}});
$('#mode').addEventListener('change',e=>{state.mode=e.target.value;save();renderWorkout();});
$('.day-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const keys=Object.keys(DAYS),i=keys.indexOf(state.day);state.day=e.key==='Home'?'a':e.key==='End'?'d':keys[(i+(e.key==='ArrowRight'?1:3))%4];save();renderWorkout();$(`#tab-${state.day}`).focus({preventScroll:true});$('#day-title').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
$('#search').addEventListener('input',renderLibrary);$('#group-filter').addEventListener('change',renderLibrary);
$('#reset-day').addEventListener('click',()=>{if(!confirm('Reset today’s checked sets and repetition entries for this day and training view? Saved weight choices will remain.'))return;for(const key of Object.keys(state.logs)){if(key.startsWith([date,state.mode,state.day,''].join('|')))delete state.logs[key];}save();renderWorkout();toast('Today’s sets reset.');});
$('#clear-data').addEventListener('click',()=>{if(!confirm('Clear all saved sets, repetitions, weights and exercise choices on this browser?'))return;state.mode='reduced';state.day='a';state.choices={};state.optional={};state.logs={};state.weights={};try{localStorage.removeItem(KEY);}catch{}renderWorkout();toast('Saved workout data cleared.');});
$('#close-dialog').onclick=()=>$('#exercise-dialog').close();$('#exercise-dialog').addEventListener('close',()=>$('#dialog-content').replaceChildren());
$('#exercise-dialog').addEventListener('click',e=>{if(e.target===$('#exercise-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#timer-start').onclick=()=>{if(deadline){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));deadline=null;clearInterval(timerInterval);paintTimer();}else startTimer(remaining||Number($('#timer-duration').value));};
$('#timer-reset').onclick=()=>{deadline=null;clearInterval(timerInterval);remaining=Number($('#timer-duration').value);paintTimer();};$('#timer-duration').onchange=()=>$('#timer-reset').click();
document.addEventListener('visibilitychange',()=>{tick();if(today()!==date){date=today();renderWorkout();}});
$('#load-form').onsubmit=e=>{e.preventDefault();const weight=Number($('#load-weight').value),step=Number($('#load-step').value);if(!Number.isFinite(weight)||!Number.isFinite(step)||weight<0||step<=0){$('#load-result').textContent='Enter a valid non-negative weight and a positive increment.';return;}let result;if(!$('#load-stable').checked)result='Do not increase. If symptoms worsened, reduce or omit the movement and follow the assessment/rehabilitation plan.';else if(!$('#load-ready').checked)result='Keep the current load and build controlled repetitions. There is no need to increase every visit.';else if(weight===0)result='For a bodyweight exercise, progress control or a suitable variation before external load. Start weighted movements with a light practice set.';else if(step/weight>.1)result=`That is a ${Math.round(step/weight*100)}% jump. Look for a smaller increment, or keep ${weight} kg and consolidate repetitions. Do not force a large jump.`;else result=`Consider ${Math.round((weight+step)*100)/100} kg next time using the same setup. Return toward the lower end of the rep range. If form or symptoms worsen, revert. This is a progression suggestion, not medical clearance.`;$('#load-result').textContent=result;};
document.addEventListener('error',event=>{const img=event.target;if(img.dataset?.inlineImage){img.closest('.inline-stage').innerHTML='<p>Animation unavailable. Use the form guide linked below and the technique notes on this card.</p>';}},true);
renderWorkout();renderLibrary();renderGallery();paintTimer();
